# Generated by Django 4.2.7 on 2026-01-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('external', 'External User'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
