# Generated by Django 6.0.2 on 2026-06-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('alumni', 'Alumni'), ('external', 'External User')], default='student', max_length=10),
        ),
    ]
