services:
  - type: web
    name: gradbridge-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn gradbridge.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9