# Generated by Django 4.2.7 on 2026-01-23 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('alumni_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='profiles.alumniprofile')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'mentorship_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_company', models.CharField(blank=True, max_length=200)),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('recommendation_letter', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('alumni_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to='profiles.alumniprofile')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'referral_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_profile', 'status'], name='referral_re_student_b7d334_idx'), models.Index(fields=['alumni_profile', 'status'], name='referral_re_alumni__ef71fd_idx'), models.Index(fields=['status'], name='referral_re_status_e39fae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentorship_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentorship.mentorshiprequest')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='messages_sender__89e028_idx'), models.Index(fields=['mentorship_request'], name='messages_mentors_c991be_idx'), models.Index(fields=['is_read', 'created_at'], name='messages_is_read_2c664b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['student_profile', 'status'], name='mentorship__student_46c376_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['alumni_profile', 'status'], name='mentorship__alumni__3c682f_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['status'], name='mentorship__status_9d5f67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshiprequest',
            unique_together={('student_profile', 'alumni_profile')},
        ),
    ]
