# Generated by Django 6.0.2 on 2026-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Internship', 'Internship'), ('Entry-level', 'Entry-level'), ('Remote', 'Remote')], default='Full-time', max_length=50),
        ),
    ]
