# Generated by Django 4.2.7 on 2026-01-23 15:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('expertise_areas', models.TextField(blank=True)),
                ('available_for_mentorship', models.BooleanField(default=True)),
                ('available_for_referrals', models.BooleanField(default=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('students_mentored_count', models.IntegerField(default=0)),
                ('referrals_made_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alumni_profiles',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('profile_strength', models.IntegerField(default=0)),
                ('profile_completion_percentage', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='student_profiles', to='profiles.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_by', models.CharField(default='system', max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'skill_gaps',
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='skills_name_2b8674_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='skills_categor_b4d9fb_idx'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='alumni_profiles', to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['batch'], name='student_pro_batch_58c288_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['graduation_year'], name='student_pro_graduat_f2df05_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['profile_strength'], name='student_pro_profile_76ac2f_idx'),
        ),
        migrations.AddIndex(
            model_name='skillgap',
            index=models.Index(fields=['student_profile', 'priority'], name='skill_gaps_student_1b109f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillgap',
            unique_together={('student_profile', 'skill')},
        ),
        migrations.AddIndex(
            model_name='alumniprofile',
            index=models.Index(fields=['current_company'], name='alumni_prof_current_a019bd_idx'),
        ),
        migrations.AddIndex(
            model_name='alumniprofile',
            index=models.Index(fields=['industry'], name='alumni_prof_industr_bb418b_idx'),
        ),
        migrations.AddIndex(
            model_name='alumniprofile',
            index=models.Index(fields=['available_for_mentorship'], name='alumni_prof_availab_92c612_idx'),
        ),
        migrations.AddIndex(
            model_name='alumniprofile',
            index=models.Index(fields=['available_for_referrals'], name='alumni_prof_availab_0422ce_idx'),
        ),
    ]
