# Generated by Django 4.2.7 on 2026-01-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alumniprofile_city_alumniprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
