# Generated by Django 6.0.2 on 2026-04-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('exp_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Full-time Job'), ('part_time', 'Part-time Job'), ('teaching', 'Teaching/TA'), ('volunteering', 'Volunteering'), ('leadership', 'Leadership/Club')], default='internship', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
