# Generated by Django 6.0.2 on 2026-04-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_studentprofile_profile_breakdown_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
